import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import { quicksand } from '@/fonts'

export const metadata: Metadata = {
  title: 'Culinary Heaven',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-primary text-secondary ${quicksand.className}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
